sudo: required
services:
    - docker

before_install:
    - docker build -t brianngo313/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true brianngo313/react-test npm test

after_success:
    - docker build -t brianngo313/multi-client ./client
    - docker build -t brianngo313/multi-nginx ./nginx
    - docker build -t brianngo313/multi-server ./server
    - docker build -t brianngo313/multi-worker ./worker
    # Docker login
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push brianngo313/multi-client
    - docker push brianngo313/multi-nginx
    - docker push brianngo313/multi-server
    - docker push brianngo313/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-482825355239
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
